//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starbucks.BaristaServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Hermes.Messaging.Wcf", ConfigurationName="BaristaServiceProxy.BaristaService")]
    public interface BaristaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Hermes.Messaging.Wcf/BaristaService/Put", ReplyAction="Hermes.Messaging.Wcf/BaristaService/PutResponse")]
        int Put(Starbucks.Messages.PlaceOrder command);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hermes.Messaging.Wcf/BaristaService/Put", ReplyAction="Hermes.Messaging.Wcf/BaristaService/PutResponse")]
        System.Threading.Tasks.Task<int> PutAsync(Starbucks.Messages.PlaceOrder command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BaristaServiceChannel : Starbucks.BaristaServiceProxy.BaristaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaristaServiceClient : System.ServiceModel.ClientBase<Starbucks.BaristaServiceProxy.BaristaService>, Starbucks.BaristaServiceProxy.BaristaService {
        
        public BaristaServiceClient() {
        }
        
        public BaristaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaristaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaristaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaristaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Put(Starbucks.Messages.PlaceOrder command) {
            return base.Channel.Put(command);
        }
        
        public System.Threading.Tasks.Task<int> PutAsync(Starbucks.Messages.PlaceOrder command) {
            return base.Channel.PutAsync(command);
        }
    }
}
